### ISSUE TITLE
FireInTheRealm 비활성화

### ISSUE THREAD

**Issue by conquerex** [Nexters/Yetda_Android#57]
확실히 쓰는지 안쓰는지 확인하고 주석 처리 등으로 비활성화

**반드시 파이어베이스 이슈 해결 후 처리 할 것!!!!**

**Comment by DohyunYoun** [comment]
firebase -> realm에 저장하는 로직을 새로 생성한 도메인 패키지에서 처리하도록 수정 (FireInTheRealm)
