### ISSUE TITLE
[crashlytics] 데이터 가져올때 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DohyunYoun** [Nexters/Yetda_Android#62]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
Out of range in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp line 103(requested: 29 valid: 29)
io.realm.internal.OsResults.nativeGetRow

- [crashlytics](https://console.firebase.google.com/u/1/project/yetda-d4506/crashlytics/app/android:com.nexters.yetda.android/issues/03861c1b9a8fef3b1f34e13a2e8fefcc?time=last-seven-days&sessionEventKey=6155B7410125000114941F42572B8A7E_1592159310808365947)
```
com.nexters.yetda.android.domain.database.dao.QuestionDao.findQuestion (QuestionDao.kt:61)
com.nexters.yetda.android.ui.question.QuestionViewModel.findQuestion (QuestionViewModel.kt:49)
com.nexters.yetda.android.ui.question.QuestionActivity.findQuestionAndPresents (QuestionActivity.kt:120)
com.nexters.yetda.android.ui.question.QuestionActivity.initViewFinal$lambda-4$lambda-3 (QuestionActivity.kt:92)
```

추측1 :  findQuestion시에 results를 뽑아오는데, 이때 결과값이 비어있는데 랜덤값으로 뽑아와서 문제가 되지 않을까 .. ?

**Comment by conquerex** [comment]
Question(id=1, question='감성적인 사람인가요?', tag='감성', isAsked=false)
Question(id=2, question='이불 밖은 위험하다고 생각하나요?', tag='집순이', isAsked=false)
Question(id=3, question='실용적인 물건을 좋아하나요?', tag='실용', isAsked=false)
Question(id=4, question='먹고 마시는 선물을 줘도 좋아할까요?', tag='식품', isAsked=false)
Question(id=5, question='한 입 베어문 사과와 스티븐 잡스를 좋아하나요?', tag='앱등이', isAsked=false)
Question(id=6, question='외향적인가요?', tag='인싸', isAsked=false)
Question(id=7, question='내향적인가요?', tag='아싸', isAsked=false)
Question(id=8, question='단 음식을 잘 드시나요?', tag='디저트', isAsked=false)
Question(id=9, question='직접 만날 수 없는 상황인가요?', tag='원격', isAsked=false)
Question(id=10, question='게임을 많이 하는편인가요?', tag='게임', isAsked=false)
Question(id=11, question='자신을 꾸미는데 많은 신경을 쓰나요?', tag='뷰티', isAsked=false)
Question(id=12, question='뭣이 중헌디..건강이 중요하지!! 라고 생각하나요?', tag='건강', isAsked=false)
Question(id=13, question='직접 요리하는 것을 즐기나요?', tag='요리', isAsked=false)
Question(id=14, question='운동이 취미인가요?', tag='운동', isAsked=false)
Question(id=15, question='여행을 자주 다니나요?', tag='여행', isAsked=false)
Question(id=16, question='패숑파숑! 패셔너블한 사람인가요?', tag='패션', isAsked=false)
Question(id=17, question='패션의 완성에 액세서리는 빠질 수 없다고 생각하나요?', tag='액세서리', isAsked=false)
Question(id=18, question='어떤 분야에 전문가 이상의 열정과 흥미를 가지고 있나요?', tag='덕질', isAsked=false)
Question(id=19, question='호주머니에 코끼리 빼고 다 담을 수 있다고 생각하나요?', tag='가방', isAsked=false)
Question(id=20, question='취'향'이 확고한 사람인가요?', tag='향', isAsked=false)
Question(id=21, question='피부관리에 신경쓰는 사람인가요?', tag='피부', isAsked=false)
Question(id=22, question='직접 얼굴보고 만나고 싶은 사람인가요?', tag='대면', isAsked=false)
Question(id=23, question='음악을 좋아하나요?', tag='음악', isAsked=false)
Question(id=24, question='손수 만든 것을 좋아하나요?', tag='수제', isAsked=false)
Question(id=25, question='세상에 단 하나뿐인 것에 웃음이 활짝 필까요?', tag='커스텀', isAsked=false)
Question(id=26, question='무언가 남기고 기록하는 것을 좋아하나요?', tag='기록', isAsked=false)
Question(id=27, question='컴퓨터와 사이가 좋습니까?', tag='컴퓨터', isAsked=false)
Question(id=28, question='핸드폰이 손에서 떨어지지 않습니까?', tag='핸드폰', isAsked=false)
Question(id=29, question='인플루언서의 기질이 다분합니까?', tag='관종', isAsked=false)
Question(id=30, question='새 기계랑 바로 친구해버리는 사람인가요?', tag='전자기기', isAsked=false)
Question(id=31, question='연인인가요?', tag='연인', isAsked=false)
Question(id=32, question='재치만! 있는 선물을 준비해 볼까요?', tag='쓸없선', isAsked=false)
Question(id=33, question='문구류를 많이 사용하나요?', tag='문구', isAsked=false)
Question(id=34, question='당신의 소중한 마음을 기쁘게 받아줄까요?', tag='마음', isAsked=false)
Question(id=35, question='주변을 꾸미는 것을 좋아하나요?', tag='인테리어', isAsked=false)

Present(id=1, price=0, name='네잎클로버', tags='감성, 연인, 친구, 마음', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_clover.png?alt=media&token=db407bfa-0729-48a8-87c6-92971eeb290e')
Present(id=2, price=500000, name='돈다발', tags='실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_money.png?alt=media&token=ee4da888-399e-44ba-86ee-4d4e81d77a09')
Present(id=3, price=500000, name='텔레비전 55인치', tags='전자기기', image='')
Present(id=4, price=1600000, name='텔레비전 75인치', tags='전자기기', image='')
Present(id=5, price=40000, name='와플기계', tags='전자기기, 요리', image='')
Present(id=6, price=50000, name='에어프라이어', tags='전자기기, 요리', image='')
Present(id=7, price=40000, name='접이식 전기포트', tags='전자기기', image='')
Present(id=8, price=200000, name='커피머신', tags='전자기기', image='')
Present(id=9, price=300000, name='식기세트', tags='실용, 요리', image='')
Present(id=10, price=60000, name='다기세트', tags='실용, 요리', image='')
Present(id=11, price=500000, name='아이패드', tags='전자기기, 앱등이', image='')
Present(id=12, price=150000, name='에어팟', tags='전자기기, 앱등이', image='')
Present(id=13, price=0, name='빌딩', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_building.png?alt=media&token=26661a2f-c6c2-4655-ba58-9ea67b515170')
Present(id=14, price=300000, name='에어팟프로', tags='전자기기, 앱등이', image='')
Present(id=15, price=1500000, name='맥북', tags='전자기기, 앱등이', image='')
Present(id=16, price=250000, name='애플워치', tags='전자기기, 앱등이', image='')
Present(id=17, price=300000, name='스마트워치', tags='전자기기, 액세서리, 실용', image='')
Present(id=18, price=20000, name='와인', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=19, price=4000, name='소주', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=20, price=50000, name='잭다니엘 허니', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=21, price=500000, name='돔페리뇽 빈티지 로제', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=22, price=280000, name='돔페리뇽 빈티지', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=23, price=80000, name='모엣샹동', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=24, price=0, name='생일빵', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_punch.png?alt=media&token=0766810c-e576-4240-8175-269fddf2f6db')
Present(id=25, price=35000, name='모스카토 와인', tags='성인', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_drinks.png?alt=media&token=a0dc01d8-bf8a-427d-99ec-b1660f1ad170')
Present(id=26, price=50000000, name='드림 카', tags='성인, 차', image='')
Present(id=27, price=500000, name='신시사이저(전자피아노)', tags='전자기기, 음악', image='')
Present(id=28, price=30000, name='스피커', tags='음악', image='')
Present(id=29, price=60000, name='헤드셋', tags='음악', image='')
Present(id=30, price=160000, name='지프로 무선마우스', tags='컴퓨터, 실용, 게임', image='')
Present(id=31, price=40000, name='게이밍 마우스', tags='컴퓨터, 실용, 게임', image='')
Present(id=32, price=110000, name='로지텍 버티컬 마우스', tags='컴퓨터, 실용, 건강', image='')
Present(id=33, price=22000, name='버티컬 마우스', tags='컴퓨터, 실용, 건강', image='')
Present(id=34, price=18000, name='마우스', tags='컴퓨터, 실용', image='')
Present(id=35, price=0, name='양키캔들 세트', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_candle.png?alt=media&token=6196ab1e-1ae8-4a44-9826-693a9f694f3d')
Present(id=36, price=150000, name='태블릿', tags='컴퓨터, 실용, 기록', image='')
Present(id=37, price=450000, name='게이밍 모니터 31.5인치', tags='컴퓨터, 실용, 게임', image='')
Present(id=38, price=230000, name='게이밍 모니터 27인치', tags='컴퓨터, 실용, 게임', image='')
Present(id=39, price=200000, name='컴퓨터모니터', tags='컴퓨터, 실용', image='')
Present(id=40, price=100000, name='방송용 마이크', tags='관종', image='')
Present(id=41, price=50000, name='방송용 조명', tags='관종', image='')
Present(id=42, price=25000, name='삼각대 셀카봉', tags='관종, 실용', image='')
Present(id=43, price=150000, name='스마트폰 짐벌', tags='관종, 실용', image='')
Present(id=44, price=360000, name='닌텐도 스위치', tags='게임, 인싸, 전자기기', image='')
Present(id=45, price=230000, name='닌텐도 스위치 라이트', tags='게임, 인싸, 전자기기', image='')
Present(id=46, price=35000, name='양키캔들', tags='실용, 향', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_candle.png?alt=media&token=6196ab1e-1ae8-4a44-9826-693a9f694f3d')
Present(id=47, price=60000, name='닌텐도 게임칩', tags='게임, 인싸', image='')
Present(id=48, price=420000, name='PS4 프로', tags='게임, 아싸', image='')
Present(id=49, price=65000, name='PS4 무선 컨트롤러', tags='게임', image='')
Present(id=50, price=30000, name='보드게임', tags='게임, 인싸', image='')
Present(id=51, price=25000, name='스팀게임', tags='게임', image='')
Present(id=52, price=100000, name='쌤소나이트 브리프케이스', tags='패션, 가방, 실용', image='')
Present(id=53, price=50000, name='브리프케이스', tags='패션, 가방, 실용', image='')
Present(id=54, price=80000, name='클러치 백', tags='패션, 가방, 여성', image='')
Present(id=55, price=30000, name='캔버스 가방', tags='패션, 가방', image='')
Present(id=56, price=30000, name='록시땅 핸드크림', tags='뷰티, 실용, 피부', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_handcream.png?alt=media&token=2d030361-09d1-48dd-846c-d22fbc72651b')
Present(id=57, price=45000, name='우드윅 캔들', tags='실용, 향', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_candle.png?alt=media&token=6196ab1e-1ae8-4a44-9826-693a9f694f3d')
Present(id=58, price=12000, name='카밀 핸드크림', tags='뷰티, 실용, 피부', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_handcream.png?alt=media&token=2d030361-09d1-48dd-846c-d22fbc72651b')
Present(id=59, price=12000, name='유리아쥬 립밤', tags='뷰티, 실용, 피부', image='')
Present(id=60, price=4000, name='버츠비 비즈왁스 립밤', tags='뷰티, 실용, 피부', image='')
Present(id=61, price=4000, name='버츠비 자몽 립밤', tags='뷰티, 실용, 향, 피부', image='')
Present(id=62, price=0, name='스킨케어', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_skincare.png?alt=media&token=0888df6d-e0b8-40cd-8be7-2d01823e0362')
Present(id=63, price=9000, name='아벤느 미스트', tags='실용, 피부', image='')
Present(id=64, price=29000, name='메이크업포에버 픽스 미스트', tags='실용, 여성, 피부', image='')
Present(id=65, price=5000, name='AHC 아이크림', tags='실용, 여성, 피부', image='')
Present(id=66, price=40000, name='나랑 밥 한 끼!', tags='대면', image='')
Present(id=67, price=20000, name='나랑 커피 한 잔!', tags='대면', image='')
Present(id=68, price=37000, name='캔들 워머', tags='실용, 인테리어', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_candle.png?alt=media&token=6196ab1e-1ae8-4a44-9826-693a9f694f3d')
Present(id=69, price=30000, name='나랑 영화 한 편!', tags='대면', image='')
Present(id=70, price=60000, name='후드', tags='패션, 캐주얼', image='')
Present(id=71, price=70000, name='맨투맨', tags='패션, 캐주얼', image='')
Present(id=72, price=60000, name='펌프스 구두', tags='격식', image='')
Present(id=73, price=200000, name='캐주얼 정장', tags='격식', image='')
Present(id=74, price=30000, name='셔츠', tags='실용', image='')
Present(id=75, price=30000, name='넥타이', tags='실용, 남성', image='')
Present(id=76, price=100000, name='신발', tags='패션, 실용', image='')
Present(id=77, price=8000, name='캐리어 네임택', tags='여행, 실용', image='')
Present(id=78, price=30000, name='여권케이스', tags='여행', image='')
Present(id=79, price=30000, name='직접 만든 향초', tags='수제', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_candle.png?alt=media&token=6196ab1e-1ae8-4a44-9826-693a9f694f3d')
Present(id=80, price=20000, name='디퓨저', tags='실용, 향', image='')
Present(id=81, price=80000, name='조말론 디퓨저', tags='실용, 향', image='')
Present(id=82, price=0, name='학천마리', tags='감성, 연인, 마음', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_hak.png?alt=media&token=bc14cc54-efa5-4d57-89a3-3563b0aeaf3c')
Present(id=83, price=5000, name='차량용방향제', tags='향', image='')
Present(id=84, price=30000, name='무드등', tags='감성, 인테리어', image='')
Present(id=85, price=50000, name='커스텀 무드등', tags='감성, 커스텀', image='')
Present(id=86, price=50000, name='LP판', tags='감성, 음악', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_lp.png?alt=media&token=8a802135-57ce-4aff-9c3c-ba59702e3401')
Present(id=87, price=180000, name='폴라로이드카메라', tags='감성, 기록', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_camera.png?alt=media&token=3a16b16f-e43f-4c92-84d7-341b73dd7242')
Present(id=88, price=90000, name='폴라로이드 카메라 미니', tags='감성, 기록', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_camera.png?alt=media&token=3a16b16f-e43f-4c92-84d7-341b73dd7242')
Present(id=89, price=650000, name='캐논 EOS M50', tags='기록', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_camera.png?alt=media&token=3a16b16f-e43f-4c92-84d7-341b73dd7242')
Present(id=90, price=220000, name='캐논 EOS 600D', tags='기록', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_camera.png?alt=media&token=3a16b16f-e43f-4c92-84d7-341b73dd7242')
Present(id=91, price=20000, name='폰케이스', tags='핸드폰', image='')
Present(id=92, price=15000, name='커스텀 폰케이스', tags='핸드폰, 커스텀', image='')
Present(id=93, price=0, name='손편지', tags='마음', image='')
Present(id=94, price=25000, name='커스텀 드로잉 폰케이스', tags='핸드폰, 커스텀', image='')
Present(id=95, price=12000, name='그립톡', tags='핸드폰', image='')
Present(id=96, price=10000, name='커스텀 그립톡', tags='핸드폰, 커스텀', image='')
Present(id=97, price=50000, name='정관장', tags='건강, 실용, 식품', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_vitamin.png?alt=media&token=7de4a8cf-eb57-438c-b3e9-9c7186aedbc9')
Present(id=98, price=40000, name='영양제', tags='건강, 식품', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_vitamin.png?alt=media&token=7de4a8cf-eb57-438c-b3e9-9c7186aedbc9')
Present(id=99, price=30000, name='종합비타민', tags='건강, 식품', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_vitamin.png?alt=media&token=7de4a8cf-eb57-438c-b3e9-9c7186aedbc9')
Present(id=100, price=50000, name='마사지기', tags='건강, 실용', image='')
Present(id=101, price=15000, name='손풍기', tags='여름, 실용', image='')
Present(id=102, price=40000, name='수영복', tags='여름', image='')
Present(id=103, price=20000, name='다이어리', tags='겨울, 기록', image='')
Present(id=104, price=10000, name='머니건', tags='쓸없선', image='')
Present(id=105, price=10000, name='달력', tags='겨울', image='')
Present(id=106, price=10000, name='직접 만든 달력', tags='수제', image='')
Present(id=107, price=300000, name='롱패딩', tags='겨울, 실용', image='')
Present(id=108, price=150000, name='경량 롱패딩', tags='겨울, 실용', image='')
Present(id=109, price=20000, name='목도리/장갑', tags='겨울, 실용', image='')
Present(id=110, price=30000, name='손수 짠 목도리', tags='수제', image='')
Present(id=111, price=20000, name='내복', tags='겨울, 실용, 집순이', image='')
Present(id=112, price=25000, name='베드트레이', tags='집순이, 실용', image='')
Present(id=113, price=60000, name='미니 빔 프로젝터', tags='집순이, 실용', image='')
Present(id=114, price=10000, name='스마트폰 거치대', tags='집순이, 실용', image='')
Present(id=115, price=20000, name='예쁜 쓰레기', tags='쓸없선', image='')
Present(id=116, price=30000, name='잠옷', tags='집순이', image='')
Present(id=117, price=25000, name='속옷', tags='연인', image='')
Present(id=118, price=40000, name='커플속옷', tags='연인', image='')
Present(id=119, price=60000, name='커플잠옷', tags='연인', image='')
Present(id=120, price=100000, name='커플링', tags='연인', image='')
Present(id=121, price=8000, name='아이스크림쿠폰', tags='원격, 식품', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_giftycon.png?alt=media&token=aea39a99-4848-4395-a9e4-506e6b073712')
Present(id=122, price=3000, name='카카오톡 이모티콘', tags='원격', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_emoji.png?alt=media&token=10531f5c-c5a5-4eec-88e5-aa262ea36a09')
Present(id=123, price=20000, name='기프티콘', tags='원격, 실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_giftycon.png?alt=media&token=aea39a99-4848-4395-a9e4-506e6b073712')
Present(id=124, price=0, name='치킨 기프티콘', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_giftycon.png?alt=media&token=aea39a99-4848-4395-a9e4-506e6b073712')
Present(id=125, price=0, name='케이크', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_ordercake.png?alt=media&token=59d9538f-e822-4e9b-ab19-c588f80fa932')
Present(id=126, price=10000, name='관종모자', tags='쓸없선', image='')
Present(id=127, price=50000, name='주문케이크', tags='커스텀', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_ordercake.png?alt=media&token=59d9538f-e822-4e9b-ab19-c588f80fa932')
Present(id=128, price=70000, name='핸드메이드 케이크', tags='수제', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_ordercake.png?alt=media&token=59d9538f-e822-4e9b-ab19-c588f80fa932')
Present(id=129, price=60000, name='향수', tags='뷰티, 향', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_perfume.png?alt=media&token=3cb602ea-2fee-4279-b1ff-bd769a729f49')
Present(id=130, price=30000, name='립스틱', tags='뷰티, 여성', image='')
Present(id=131, price=50000, name='목걸이', tags='패션, 액세서리', image='')
Present(id=132, price=20000, name='귀걸이', tags='패션, 액세서리, 여성', image='')
Present(id=133, price=30000, name='피어씽', tags='패션, 액세서리', image='')
Present(id=134, price=30000, name='시계', tags='패션, 액세서리, 실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_watch.png?alt=media&token=550f23fb-6fdd-44af-8a8a-0f9122859e64')
Present(id=135, price=40000, name='로이드 시계', tags='패션, 액세서리, 실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_watch.png?alt=media&token=550f23fb-6fdd-44af-8a8a-0f9122859e64')
Present(id=136, price=300000, name='티쏘 시계', tags='패션, 액세서리, 실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_watch.png?alt=media&token=550f23fb-6fdd-44af-8a8a-0f9122859e64')
Present(id=137, price=0, name='전남친사진', tags='쓸없선, 마음', image='')
Present(id=138, price=3500000, name='오메가 시계', tags='패션, 액세서리, 실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_watch.png?alt=media&token=550f23fb-6fdd-44af-8a8a-0f9122859e64')
Present(id=139, price=30000, name='팔찌', tags='패션, 액세서리', image='')
Present(id=140, price=60000, name='선글라스', tags='패션', image='')
Present(id=141, price=0, name='지갑', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_wallet.png?alt=media&token=cfdac30b-e38a-49bb-be6f-5c9b804f5bfb')
Present(id=142, price=500000, name='명품지갑', tags='패션', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_wallet.png?alt=media&token=cfdac30b-e38a-49bb-be6f-5c9b804f5bfb')
Present(id=143, price=100000, name='블루투스이어폰', tags='실용', image='')
Present(id=144, price=1200000, name='노트북', tags='실용', image='')
Present(id=145, price=150000, name='구찌지우개', tags='문구', image='')
Present(id=146, price=75000, name='에르메스 연필', tags='문구', image='')
Present(id=147, price=30000, name='만년필', tags='문구', image='')
Present(id=148, price=60000, name='슈프림벽돌', tags='쓸없선', image='')
Present(id=149, price=20000, name='마카롱', tags='식품, 디저트', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_desert.png?alt=media&token=b49716c1-d6bd-4692-94c9-48c61178a78e')
Present(id=150, price=30000, name='차(마시는)', tags='식품', image='')
Present(id=151, price=100000, name='안마기', tags='실용, 건강, 전자기기', image='')
Present(id=152, price=100000, name='전기면도기', tags='실용, 남성, 전자기기', image='')
Present(id=153, price=10000, name='면도기', tags='실용', image='')
Present(id=154, price=30000, name='풍경', tags='인테리어', image='')
Present(id=155, price=15000, name='화분', tags='인테리어', image='')
Present(id=156, price=25000, name='샤워 가운', tags='패션', image='')
Present(id=157, price=0, name='텀블러', tags='', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_cub.png?alt=media&token=a0a7dcfa-24b7-4cfa-a1a1-e2de0d1a5b39')
Present(id=158, price=15000, name='책', tags='마음', image='')
Present(id=159, price=100000, name='현금', tags='실용', image='https://firebasestorage.googleapis.com/v0/b/yetda-d4506.appspot.com/o/present_money.png?alt=media&token=ee4da888-399e-44ba-86ee-4d4e81d77a09')
Present(id=160, price=100000, name='인형/피규어', tags='덕질', image='')
Present(id=161, price=20000, name='러그', tags='인테리어', image='')
Present(id=162, price=150000, name='콘서트 티켓', tags='음악', image='')
Present(id=163, price=20000, name='앨범', tags='감성', image='')
Present(id=164, price=30000, name='꽃다발', tags='감성', image='')
Present(id=165, price=10000, name='초콜릿', tags='식품, 디저트', image='')
Present(id=166, price=250000, name='LED마스크팩', tags='전자기기, 40+', image='')
Present(id=167, price=40000, name='레깅스', tags='운동, 여성', image='')
Present(id=168, price=40000, name='언더아머 운동복', tags='운동, 남성', image='')
Present(id=169, price=20000, name='요가매트', tags='운동, 실용', image='')

**Comment by DohyunYoun** [comment]
Realm객체는 자동으로 갱신되어 이후 transaction 수행 하면 기존 객체가 자동으로 변경된다. 그래서 index오류가 발생하였음.

[ref](https://academy.realm.io/kr/posts/threading-deep-dive/)
